wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.17.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726498779
    t:
      1:
      - 12
      - 45
      - 50
      - 55
      2:
      - 12
      - 45
      - 50
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.0
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
BETA:
  desc: null
  value: 0.5
BUFFER_BATCH_SIZE:
  desc: null
  value: 256
BUFFER_SIZE:
  desc: null
  value: 2048
EXPECTILE:
  desc: null
  value: 0.1
GAMMA:
  desc: null
  value: 0.995
LR:
  desc: null
  value: 0.0001
MAX_GRAD_NORM:
  desc: null
  value: 5
NUM_ENVS:
  desc: null
  value: 8
POLICY_HIDDEN:
  desc: null
  value: 64
Q_HIDDEN_DIM:
  desc: null
  value: 128
Q_LR:
  desc: null
  value: 1.0e-06
TARGET_UPDATE_INTERVAL:
  desc: null
  value: 20
V_HIDDEN_DIM:
  desc: null
  value: 64
V_LR:
  desc: null
  value: 1.0e-06
