"DEBUG": True
"DISABLE_JIT": False
"NUM_SEEDS": 5
"SEED": 30
"ENV_NAME": "halfcheetah"
"TEST_ENV_NAME": "halfcheetah"
"ENV_KWARGS": {}


# where to save the params (if None, will not save)
"SAVE_PATH": "results/DQN/dqn_network"


# other params
"NUM_ENVS": 8
"NUM_STEPS": 256
"BUFFER_SIZE": 1024
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 5e6
"AGENT_HIDDEN_DIM": 64
"AGENT_INIT_SCALE": 2.
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
"EPSILON_ANNEAL_TIME": 100000
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 200
"LR": 0.0005
"LR_LINEAR_DECAY": False
"EPS_ADAM": 0.0001
"WEIGHT_DECAY_ADAM": 0.00001
"TD_LAMBDA_LOSS": False
"TD_LAMBDA": 0.6
"GAMMA": 0.99
"VERBOSE": False
"WANDB_ONLINE_REPORT": True
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 50000

"WANDB_MODE": "online"  # enable this line in training
"ENTITY": "marlhf"
"PROJECT": "DQN"
"PROJECT_PREFIX": ""

"IL_NETWORK_HIDDEN": 128
"IL_NETWORK_SAVE_PATH": "results/IL_configs/student_network"

"TRAIN": False
"GYM_NAME": "HalfCheetah"
"DEBUG_STEPS": 10e4
"RENDER": False
"ALG_NAME": "dqn"