"DEBUG": False
"DISABLE_JIT": False
"NUM_SEEDS": 1
"SEED": 30
"ENV_NAME": "inverted_pendulum"
"TEST_ENV_NAME": "inverted_pendulum"
"ENV_KWARGS": {}


# where to save the params (if None, will not save)
"SAVE_PATH": "results/DQN/dqn_network"


# other params
"NUM_ENVS": 8
"NUM_STEPS": 10
"BUFFER_SIZE": 512
"DEBUG_BUFFER_SIZE": 512
"BUFFER_BATCH_SIZE": 32
"TOTAL_TIMESTEPS": 1e6
"Q_HIDDEN_DIM": 32
"V_HIDDEN_DIM": 32
"AGENT_INIT_SCALE": 1.
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 4
"LR": 0.000005
"Q_LR": 0.000000001
"V_LR": 0.000000001
"LR_LINEAR_DECAY": False
"EPS_ADAM": 0.0001
"WEIGHT_DECAY_ADAM": 0.00001
"TD_LAMBDA_LOSS": False
"TD_LAMBDA": 0.6
"BETA": 1
"GAMMA": 0.99
"VERBOSE": False
"WANDB_ONLINE_REPORT": True
"NUM_TEST_EPISODES": 32
"TEST_INTERVAL": 50000
"POLICY_HIDDEN": 64
"EXPECTILE": 0.1
"NUM_EPOCHS": 16

"WANDB_MODE": "online"  # enable this line in training
"ENTITY": "marlhf"
"PROJECT": "DQN"
"PROJECT_PREFIX": ""
"TUNE_PROJECT": "DQN_tune1"

"IL_NETWORK_HIDDEN": 128
"IL_NETWORK_SAVE_PATH": "results/IL_configs/student_network"

"TRAIN": True
"GYM_NAME": "HalfCheetah"
"DEBUG_STEPS": 10e3
"RENDER": True
"ALG_NAME": "dqn"