"DEBUG": False
"DISABLE_JIT": False
"SEED": 3
"ENV_NAME": "halfcheetah-medium-expert-v2"
"TEST_ENV_NAME": "halfcheetah"
# "ENV_NAME": "hopper-medium-expert-v2"
# "TEST_ENV_NAME": "hopper"
# "ENV_NAME": "antmaze-umaze-v2"
# "TEST_ENV_NAME": "ant"
"ENV_KWARGS": {}

"LR": 1e-3
"LR_LINEAR_DECAY": False
"MAX_GRAD_NORM": 25
"TOTAL_TIMESTEPS": 1e7
"NUM_STEPS": 128
"NUM_ENVS": 128
"NUM_EPOCHS": 100
# "NUM_TEST_ENVS": 10
"NUM_TEST_ENVS": 128
"NUM_TEST_STEPS": 130
"BATCH_SIZE": 10
"TEST_INTERVAL": 1
"SHUFFLE_SEED": 5
"RENDER": True

"WANDB_MODE": "online"  # enable this line in training
"ENTITY": "marlhf"
"PROJECT": "IL_offline"
"TUNE_PROJECT": "IL_offline_tune1"
"PROJECT_PREFIX": ""

"STUDENT_NETWORK_HIDDEN": 128
"STUDENT_NETWORK_SAVE_PATH": "results/IL_configs/student_network"