wandb_version: 1

DEBUG:
  desc: null
  value: false
DISABLE_JIT:
  desc: null
  value: false
SEED:
  desc: null
  value: 3
ENV_NAME:
  desc: null
  value: halfcheetah-medium-expert-v2
TEST_ENV_NAME:
  desc: null
  value: halfcheetah
ENV_KWARGS:
  desc: null
  value: {}
LR:
  desc: null
  value: 0.001
LR_LINEAR_DECAY:
  desc: null
  value: false
MAX_GRAD_NORM:
  desc: null
  value: 25
TOTAL_TIMESTEPS:
  desc: null
  value: 10000000.0
NUM_STEPS:
  desc: null
  value: 128
NUM_ENVS:
  desc: null
  value: 128
NUM_EPOCHS:
  desc: null
  value: 100
NUM_TEST_ENVS:
  desc: null
  value: 128
NUM_TEST_STEPS:
  desc: null
  value: 1000
BATCH_SIZE:
  desc: null
  value: 10
TEST_INTERVAL:
  desc: null
  value: 1
SHUFFLE_SEED:
  desc: null
  value: 5
WANDB_MODE:
  desc: null
  value: online
ENTITY:
  desc: null
  value: marlhf
PROJECT:
  desc: null
  value: IL_offline
TUNE_PROJECT:
  desc: null
  value: IL_offline_tune1
PROJECT_PREFIX:
  desc: null
  value: ''
STUDENT_NETWORK_HIDDEN:
  desc: null
  value: 128
STUDENT_NETWORK_SAVE_PATH:
  desc: null
  value: results/IL_configs/student_network
TRAIN:
  desc: null
  value: true
RENDER:
  desc: null
  value: true
ALG_NAME:
  desc: null
  value: offline_il
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.17.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726764848
    t:
      1:
      - 12
      - 45
      - 50
      - 55
      2:
      - 12
      - 45
      - 50
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.10.0
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
