wandb_version: 1

BETA:
  value: 5
BUFFER_BATCH_SIZE:
  value: 256
BUFFER_SIZE:
  value: 1024
EXPECTILE:
  value: 0.05
GAMMA:
  value: 0.99
LR:
  value: 0.0001
MAX_GRAD_NORM:
  value: 10
NUM_ENVS:
  value: 8
POLICY_HIDDEN:
  value: 256
Q_HIDDEN_DIM:
  value: 128
Q_LR:
  value: 1.0e-05
TARGET_UPDATE_INTERVAL:
  value: 10
V_HIDDEN_DIM:
  value: 32
V_LR:
  value: 0.001
