wandb_version: 1

BETA:
  value: 1
BUFFER_BATCH_SIZE:
  value: 32
BUFFER_SIZE:
  value: 512
EXPECTILE:
  value: 0.25
GAMMA:
  value: 0.99
LR:
  value: 0.0001
MAX_GRAD_NORM:
  value: 10
NUM_ENVS:
  value: 32
POLICY_HIDDEN:
  value: 64
Q_HIDDEN_DIM:
  value: 128
Q_LR:
  value: 0.0001
TARGET_UPDATE_INTERVAL:
  value: 20
V_HIDDEN_DIM:
  value: 128
V_LR:
  value: 1.0e-06
