wandb_version: 1

BETA:
  value: 5
BUFFER_BATCH_SIZE:
  value: 64
BUFFER_SIZE:
  value: 512
EXPECTILE:
  value: 0.1
GAMMA:
  value: 0.99
LR:
  value: 1.0e-05
MAX_GRAD_NORM:
  value: 1
NUM_ENVS:
  value: 8
POLICY_HIDDEN:
  value: 256
Q_HIDDEN_DIM:
  value: 32
Q_LR:
  value: 1.0e-05
TARGET_UPDATE_INTERVAL:
  value: 20
V_HIDDEN_DIM:
  value: 64
V_LR:
  value: 0.0001
