wandb_version: 1

BETA:
  value: 1
BUFFER_BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 2048
EXPECTILE:
  value: 0.1
GAMMA:
  value: 0.995
LR:
  value: 1.0e-05
MAX_GRAD_NORM:
  value: 1
NUM_ENVS:
  value: 16
POLICY_HIDDEN:
  value: 64
Q_HIDDEN_DIM:
  value: 128
Q_LR:
  value: 0.0001
TARGET_UPDATE_INTERVAL:
  value: 4
V_HIDDEN_DIM:
  value: 32
V_LR:
  value: 1.0e-06
