wandb_version: 1

BETA:
  value: 5
BUFFER_BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 2048
EXPECTILE:
  value: 0.25
GAMMA:
  value: 0.995
LR:
  value: 1.0e-05
MAX_GRAD_NORM:
  value: 5
NUM_ENVS:
  value: 8
POLICY_HIDDEN:
  value: 128
Q_HIDDEN_DIM:
  value: 128
Q_LR:
  value: 1.0e-05
TARGET_UPDATE_INTERVAL:
  value: 4
V_HIDDEN_DIM:
  value: 128
V_LR:
  value: 1.0e-05
