wandb_version: 1

BETA:
  value: 0.1
BUFFER_BATCH_SIZE:
  value: 32
BUFFER_SIZE:
  value: 512
EXPECTILE:
  value: 0.1
GAMMA:
  value: 0.99
LR:
  value: 0.0001
MAX_GRAD_NORM:
  value: 1
NUM_ENVS:
  value: 64
POLICY_HIDDEN:
  value: 256
Q_HIDDEN_DIM:
  value: 128
Q_LR:
  value: 1.0e-05
TARGET_UPDATE_INTERVAL:
  value: 4
V_HIDDEN_DIM:
  value: 64
V_LR:
  value: 0.0001
